prompt:
  base: |
    Please follow the following rules:
    1. Provide answers that are concise, focused, and directly related to the question. 
    Context:
    {context}

  contextualize: |
        (
            "Given a chat history and the latest user question "
            "which might reference context in the chat history, "
            "formulate a standalone question which can be understood "
            "without the chat history. Do NOT answer the question, "
            "just reformulate it if needed and otherwise return it as is."
        )